//
//  ZoomableComicImage.swift
//  xkcd
//
//  Created by Sylvan Martin on 12/2/25.
//
//
//  ZoomableComicImage.swift
//  xkcd
//

// GENERATED BY CHATGPT

import SwiftUI
import UIKit

struct ZoomableComicImage: View {
    let image: UIImage
    let imageID: AnyHashable

    var body: some View {
        GeometryReader { proxy in
            ZoomableComicImageRepresentable(
                image: image,
                imageID: imageID,
                availableSize: proxy.size
            )
        }
    }
}

private struct ZoomableComicImageRepresentable: UIViewRepresentable {
    let image: UIImage
    let imageID: AnyHashable
    let availableSize: CGSize

    func makeUIView(context: Context) -> UIScrollView {
        let scrollView = UIScrollView()

        context.coordinator.configure(scrollView)

        return scrollView
    }

    func updateUIView(_ scrollView: UIScrollView, context: Context) {
        context.coordinator.update(
            scrollView: scrollView,
            image: image,
            imageID: imageID,
            availableSize: availableSize
        )
    }

    func makeCoordinator() -> Coordinator {
        Coordinator()
    }

    fileprivate final class Coordinator: NSObject, UIScrollViewDelegate {
        private let imageView = UIImageView()
        private let containerView = UIView()

        private var currentImageID: AnyHashable?
        private var currentImage: UIImage?
        private var lastAvailableSize: CGSize = .zero

        private let outlinePadding: CGFloat = 8

        func configure(_ scrollView: UIScrollView) {
            scrollView.delegate = self

            scrollView.showsHorizontalScrollIndicator = false
            scrollView.showsVerticalScrollIndicator = false

            scrollView.bounces = true
            scrollView.bouncesZoom = true
            scrollView.alwaysBounceVertical = true
            scrollView.alwaysBounceHorizontal = true

            scrollView.decelerationRate = .normal
            scrollView.backgroundColor = .clear

            scrollView.minimumZoomScale = 1.0
            scrollView.maximumZoomScale = 6.0
            scrollView.zoomScale = 1.0

            imageView.contentMode = .scaleAspectFit

            containerView.backgroundColor = .white
            containerView.layer.borderWidth = 2
            containerView.layer.borderColor = UIColor.white.cgColor
            containerView.layer.cornerRadius = 12
            containerView.layer.masksToBounds = false

            containerView.layer.shadowColor = UIColor.black.cgColor
            containerView.layer.shadowOpacity = 0.15
            containerView.layer.shadowRadius = 8
            containerView.layer.shadowOffset = CGSize(width: 0, height: 3)

            scrollView.addSubview(containerView)
            containerView.addSubview(imageView)
        }

        func update(
            scrollView: UIScrollView,
            image: UIImage,
            imageID: AnyHashable,
            availableSize: CGSize
        ) {
            let imageChanged = currentImageID != imageID
            let sizeChanged = lastAvailableSize != availableSize

            if imageChanged {
                currentImageID = imageID
                currentImage = image
                imageView.image = image

                // Reset before laying out the new comic.
                scrollView.zoomScale = 1.0
                scrollView.minimumZoomScale = 1.0
                scrollView.maximumZoomScale = 6.0
                scrollView.contentOffset = .zero
            }

            if imageChanged || sizeChanged {
                updateFramesToFit(
                    scrollView: scrollView,
                    image: image,
                    availableSize: availableSize
                )

                if imageChanged {
                    scrollView.zoomScale = 1.0
                    scrollView.contentOffset = .zero
                }

                lastAvailableSize = availableSize
            }

            centerContent(in: scrollView)
        }

        func viewForZooming(in scrollView: UIScrollView) -> UIView? {
            containerView
        }

        func scrollViewDidZoom(_ scrollView: UIScrollView) {
            centerContent(in: scrollView)
        }

        private func updateFramesToFit(
            scrollView: UIScrollView,
            image: UIImage,
            availableSize: CGSize
        ) {
            guard image.size.width > 0, image.size.height > 0 else { return }

            let boundsSize = availableSize == .zero ? scrollView.bounds.size : availableSize
            guard boundsSize.width > 0, boundsSize.height > 0 else { return }

            let imageSize = image.size

            let xScale = boundsSize.width / imageSize.width
            let yScale = boundsSize.height / imageSize.height
            let scale = min(xScale, yScale)

            let imageWidth = imageSize.width * scale
            let imageHeight = imageSize.height * scale

            let containerWidth = imageWidth + 2 * outlinePadding
            let containerHeight = imageHeight + 2 * outlinePadding

            let containerX = max(0, (boundsSize.width - containerWidth) / 2)
            let containerY = max(0, (boundsSize.height - containerHeight) / 2)

            containerView.frame = CGRect(
                x: containerX,
                y: containerY,
                width: containerWidth,
                height: containerHeight
            )

            imageView.frame = containerView.bounds.insetBy(
                dx: outlinePadding,
                dy: outlinePadding
            )

            scrollView.contentSize = CGSize(
                width: max(boundsSize.width, containerWidth),
                height: max(boundsSize.height, containerHeight)
            )

            let minScale = min(
                boundsSize.width / containerWidth,
                boundsSize.height / containerHeight
            )

            scrollView.minimumZoomScale = minScale
            scrollView.maximumZoomScale = 6.0
        }

        private func centerContent(in scrollView: UIScrollView) {
            let boundsSize = scrollView.bounds.size
            var frame = containerView.frame

            if frame.size.width < boundsSize.width {
                frame.origin.x = (boundsSize.width - frame.size.width) / 2
            } else {
                frame.origin.x = 0
            }

            if frame.size.height < boundsSize.height {
                frame.origin.y = (boundsSize.height - frame.size.height) / 2
            } else {
                frame.origin.y = 0
            }

            containerView.frame = frame
        }
    }
}
