//
//  ZoomableComicImage.swift
//  xkcd
//
//  Created by Sylvan Martin on 12/2/25.
//

// Generated by ChatGPT

import UIKit
import SwiftUI

struct ZoomableComicImageView: UIViewRepresentable {
    let image: UIImage

    func makeUIView(context: Context) -> ZoomingScrollView {
        let scrollView = ZoomingScrollView(image: image)
        scrollView.delegate = context.coordinator
        return scrollView
    }

    func updateUIView(_ uiView: ZoomingScrollView, context: Context) {
        // If you need to change the image dynamically, update here.
    }

    func makeCoordinator() -> Coordinator {
        Coordinator()
    }

    class Coordinator: NSObject, UIScrollViewDelegate {
        func viewForZooming(in scrollView: UIScrollView) -> UIView? {
            guard let scrollView = scrollView as? ZoomingScrollView else { return nil }
            return scrollView.containerView   // zoom the container
        }

        func scrollViewDidZoom(_ scrollView: UIScrollView) {
            guard let scrollView = scrollView as? ZoomingScrollView else { return }
            scrollView.centerContent()
        }
    }
}

class ZoomingScrollView: UIScrollView {

    let imageView: UIImageView
    let containerView: UIView

    private let comicImage: UIImage
    private let outlinePadding: CGFloat = 8    // space between image and border

    init(image: UIImage) {
        self.comicImage = image

        self.imageView = UIImageView(image: image)
        self.containerView = UIView(frame: .zero)

        super.init(frame: .zero)

        showsHorizontalScrollIndicator = false
        showsVerticalScrollIndicator = false
        bouncesZoom = true
        alwaysBounceVertical = true
        alwaysBounceHorizontal = true
        backgroundColor = .clear

        // Image configuration
        imageView.contentMode = .scaleAspectFit

        // Container = white card + border
        containerView.backgroundColor = .white
        containerView.layer.borderWidth = 2
        containerView.layer.borderColor = UIColor.white.cgColor
        
        // Container = white card + border + rounded corners
        containerView.backgroundColor = .white
        containerView.layer.borderWidth = 2
        containerView.layer.borderColor = UIColor.white.cgColor
        containerView.layer.cornerRadius = 12     // 👈 rounded corners!
        containerView.layer.masksToBounds = false // so the shadow/border isn't clipped

        containerView.layer.shadowColor = UIColor.black.cgColor
        containerView.layer.shadowOpacity = 0.15
        containerView.layer.shadowRadius = 8
        containerView.layer.shadowOffset = CGSize(width: 0, height: 3)


        addSubview(containerView)
        containerView.addSubview(imageView)

        minimumZoomScale = 1.0
        maximumZoomScale = 6.0
        zoomScale = 1.0
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func layoutSubviews() {
        super.layoutSubviews()

        // Only recompute the base layout when we're at minimum zoom
        if zoomScale == minimumZoomScale {
            updateFramesToFit()
        }

        centerContent()
    }

    /// Lay out container + image with aspect-fit, and extra padding for the outline.
    private func updateFramesToFit() {
        guard comicImage.size.width > 0, comicImage.size.height > 0 else { return }

        let boundsSize = bounds.size
        let imageSize = comicImage.size

        // Aspect-fit scale of image inside the scroll bounds
        let xScale = boundsSize.width / imageSize.width
        let yScale = boundsSize.height / imageSize.height
        let scale = min(xScale, yScale)

        let imageWidth  = imageSize.width * scale
        let imageHeight = imageSize.height * scale

        // Container is slightly larger than the image (outline area)
        let containerWidth  = imageWidth + 2 * outlinePadding
        let containerHeight = imageHeight + 2 * outlinePadding

        // Center the container in the scroll view's bounds
        let containerX = max(0, (boundsSize.width  - containerWidth)  / 2)
        let containerY = max(0, (boundsSize.height - containerHeight) / 2)

        containerView.frame = CGRect(
            x: containerX,
            y: containerY,
            width: containerWidth,
            height: containerHeight
        )

        // Image is inset inside the container
        imageView.frame = containerView.bounds.insetBy(
            dx: outlinePadding,
            dy: outlinePadding
        )

        // Content size big enough to pan around when zoomed
        contentSize = CGSize(
            width: max(boundsSize.width, containerWidth),
            height: max(boundsSize.height, containerHeight)
        )

        // Make this "fit" state the minimum zoom
        let minScale = min(
            boundsSize.width / containerWidth,
            boundsSize.height / containerHeight
        )

        if minimumZoomScale != minScale {
            minimumZoomScale = minScale
        }
        if zoomScale < minScale {
            zoomScale = minScale
        }
    }

    /// Center the container when it's smaller than the scroll bounds (like Photos).
    func centerContent() {
        let boundsSize = bounds.size
        var frame = containerView.frame

        if frame.size.width < boundsSize.width {
            frame.origin.x = (boundsSize.width - frame.size.width) / 2
        } else {
            frame.origin.x = 0
        }

        if frame.size.height < boundsSize.height {
            frame.origin.y = (boundsSize.height - frame.size.height) / 2
        } else {
            frame.origin.y = 0
        }

        containerView.frame = frame
    }
}
